name: Ecosystem json file check

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  ecosystem:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run json check
        run: tox -eecosystem
